export {
	canonicalizeOptionalResourceLang,
	canonicalizeResourceLang,
	DEFAULT_RESOURCE_LANG,
	isResourceType,
	RESOURCE_CATEGORIES,
	RESOURCE_ENRICHMENT_TYPES,
	RESOURCE_ORIGINAL_CONTENT_TYPES,
	RESOURCE_SCOPES,
	RESOURCE_TRANSLATION_SOURCES,
	RESOURCE_TYPES,
	type ResourceCategory,
	type ResourceScope,
	type ResourceTranslationSource,
	type ResourceType,
	SOURCE_PLATFORMS,
	type SourcePlatform,
	ZH_HANT_RESOURCE_LANG,
} from '../shared/resource-types';
